---
image: rsprta/molecule-runner
services:
  - docker:dind

stages:
  - test
  - release

before_script:
  - docker -v
  - python3 -V
  - ansible --version
  - molecule --version

test:molecule:
  parallel:
    matrix:
      - MOLECULE_IMAGE:
          - "rsprta/alpine-ansible"
          - "rsprta/debian-ansible:bullseye"
          - "rsprta/opensuse-ansible"
        MOLECULE_SCENARIO:
          - "default"
  script:
    - molecule test -s "${MOLECULE_SCENARIO}"
  stage: test
  variables:
    DOCKER_HOST: "tcp://docker:2375"
    PY_COLORS: 1
    ANSIBLE_FORCE_COLOR: 1

release:galaxy:
  script:
    - ansible-galaxy role import --token $GALAXY_TOKEN $GITLAB_USER_LOGIN $CI_PROJECT_NAME
  stage: release
  only:
    - tags
