---
- name: Ensure dotfiles repository is cloned locally.
  ansible.builtin.git:
    repo: "{{ dotfiles_repo }}"
    dest: "{{ dotfiles_repo_local_destination }}"
    version: "{{ dotfiles_repo_version }}"
    accept_hostkey: "{{ dotfiles_repo_accept_hostkey }}"
    force: "{{ dotfiles_force_clone }}"
    recursive: "{{ dotfiles_recursive }}"
    update: yes
  become: false

- name: Find first existing script and run it
  ansible.builtin.shell:
    cmd: |
      for script in install.sh install bootstrap.sh bootstrap script/bootstrap setup.sh setup script/setup; do
        if [ -f "./$script" ]; then
          echo "Executing dotfiles setup script: $script"
          env
          bash "./$script"
          exit $?
        fi
      done
    chdir: "{{ dotfiles_repo_local_destination }}"
  register: bootstrap_output
  become: false

- name: Output from Dotfiles Bootstrap Script (stdout)
  ansible.builtin.debug:
    var: bootstrap_output.stdout_lines

- name: Error Output from Dotfiles Bootstrap Script (stderr)
  ansible.builtin.debug:
    var: bootstrap_output.stderr_lines
