---
- name: Converge
  hosts: all
  become: true

  pre_tasks:
    - name: Update apt cache.
      apt: update_cache=yes cache_valid_time=600
      when: ansible_os_family == 'Debian'

    - name: Install git
      package:
        name: git
        state: present

    - name: Create /root/.config directory
      file:
        path: /root/.config
        state: directory
        mode: 0755

  roles:
    - role: ansible-role-dotfiles
