---
- name: Verify
  hosts: all

  vars:
    dotfiles:
      - .exports
      - .functions
      - .gitattributes
      - .gitconfig
      - .gitignore
      - .iex.exs
      - .inputrc
      - .irbrc
      - .mackup.cfg
      - .nanorc
      - .node-functions
      - .open-file-path.sh
      - .pryrc
      - .ripgreprc
      - .zsh_plugins
      - .zshrc
      - .config
      - .config/bat/config
      - .config/direnv
      - .config/direnv/direnv.toml
      - .config/node/download_missing_stacktrace_file.js
      - .config/node/patcher.js
      - .config/node/readme.md
      - .config/ov/config.yml
      - .ipython/profile_default/ipython_config.py

  tasks:
    - name: Check dotfiles state
      ansible.builtin.stat:
        path: "/root/{{ item }}"
      register: dotfiles_symlinks
      with_items: "{{ dotfiles }}"

    - name: Assert that symlinks exist
      ansible.builtin.assert:
        that:
          - "item.stat.exists"
          - "not item.stat.islnk"
      loop_control:
        label: "{{ item.item }}"
      with_items: "{{ dotfiles_symlinks.results }}"
