name: CI

on:
  push:
    branches:
      - "*"

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: rsprta/molecule-runner
      options: --privileged
    strategy:
      matrix:
        MOLECULE_IMAGE: ["rsprta/debian-ansible:bullseye"]
        MOLECULE_SCENARIO: ["default"]
    env:
      PY_COLORS: 1
      ANSIBLE_FORCE_COLOR: 1
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Environment
        run: |
          docker -v
          python3 -V
          ansible --version
          molecule --version
      - name: Run Molecule Test
        run: molecule test -s "${{ matrix.MOLECULE_SCENARIO }}"

      - name: Build Changelog
        id: changelog
        uses: TriPSs/conventional-changelog-action@v4
        with:
          github-token: ${{ secrets.github_token }}
          fallback-version: "0.1.0"
          output-file: "CHANGELOG.md"

      - name: Ansible Galaxy Publish
        if: ${{steps.changelog.outputs.skipped == 'false'}}
        run: ansible-galaxy role import --token ${{ secrets.GALAXY_TOKEN }} ${{ github.actor }} ${{ github.event.repository.name }}
