name: CI

on:
  push:
    branches:
      - '*'

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: rsprta/molecule-runner
      options: --privileged
    strategy:
      matrix:
        MOLECULE_IMAGE: ["rsprta/alpine-ansible", "rsprta/debian-ansible:bullseye", "rsprta/opensuse-ansible"]
        MOLECULE_SCENARIO: ["default"]
    env:
      # DOCKER_HOST: tcp://localhost:2375
      PY_COLORS: 1
      ANSIBLE_FORCE_COLOR: 1
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup Environment
      run: |
        docker -v
        python3 -V
        ansible --version
        molecule --version
    - name: Run Molecule Test
      run: molecule test -s "${{ matrix.MOLECULE_SCENARIO }}"

  release:
    runs-on: ubuntu-latest
    needs: test
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Ansible Galaxy Import
      run: ansible-galaxy role import --token ${{ secrets.GALAXY_TOKEN }} ${{ github.actor }} ${{ github.event.repository.name }}
